mkfile_path := $(dir $(lastword $(MAKEFILE_LIST)))

APPL_COBJS +=

APPL_CXXOBJS += \
	util.o \
	WheelCtrl.o \
	RightAngleDetection.o \
	RunSelector.o \
	pidCtrl.o\
	Calibration.o\
	var_entering.o \
	move.o \
	pid_control.o \
	onoff_control.o\
	hsv_converter.o \
	color_judge.o

SRCLANG := c++

ifdef CONFIG_EV3RT_APPLICATION

# Include libraries
include $(EV3RT_SDK_LIB_DIR)/libcpp-ev3/Makefile

endif

APPL_DIR += $(mkfile_path)app $(mkfile_path)unit

COPTS += -fno-use-cxa-atexit
